// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace SkolaVanNastavnihAktivnosti.Migrations
{
    [DbContext(typeof(SkolaContext))]
    [Migration("20220108144751_v8122")]
    partial class v8122
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Aktivnost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojDanaUNedelji")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int?>("NastavnikID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SkolaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NastavnikID");

                    b.HasIndex("SkolaID");

                    b.ToTable("Aktivnost");
                });

            modelBuilder.Entity("Models.Nastavnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<float>("Ocena")
                        .HasColumnType("real");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Nastavnik");
                });

            modelBuilder.Entity("Models.Pohadja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AktivnostID")
                        .HasColumnType("int");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoslednjePlacanje")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UcenikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AktivnostID");

                    b.HasIndex("UcenikID");

                    b.ToTable("Pohadja");
                });

            modelBuilder.Entity("Models.Skola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tip")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Skola");
                });

            modelBuilder.Entity("Models.Ucenik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojTelefonaRoditelja")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImeRoditelja")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Ucenik");
                });

            modelBuilder.Entity("Models.Aktivnost", b =>
                {
                    b.HasOne("Models.Nastavnik", "Nastavnik")
                        .WithMany("Aktivnosti")
                        .HasForeignKey("NastavnikID");

                    b.HasOne("Models.Skola", "Skola")
                        .WithMany("Aktivnosti")
                        .HasForeignKey("SkolaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nastavnik");

                    b.Navigation("Skola");
                });

            modelBuilder.Entity("Models.Pohadja", b =>
                {
                    b.HasOne("Models.Aktivnost", "Aktivnost")
                        .WithMany("ListaUcenka")
                        .HasForeignKey("AktivnostID");

                    b.HasOne("Models.Ucenik", "Ucenik")
                        .WithMany("ListaAktivnosti")
                        .HasForeignKey("UcenikID");

                    b.Navigation("Aktivnost");

                    b.Navigation("Ucenik");
                });

            modelBuilder.Entity("Models.Aktivnost", b =>
                {
                    b.Navigation("ListaUcenka");
                });

            modelBuilder.Entity("Models.Nastavnik", b =>
                {
                    b.Navigation("Aktivnosti");
                });

            modelBuilder.Entity("Models.Skola", b =>
                {
                    b.Navigation("Aktivnosti");
                });

            modelBuilder.Entity("Models.Ucenik", b =>
                {
                    b.Navigation("ListaAktivnosti");
                });
#pragma warning restore 612, 618
        }
    }
}
